apiVersion: skaffold/v4beta1
kind: Config
build:
# defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: us-docker.pkg.dev/my-project-id/repo-name/market-data-transcoder
    context: ../../
    docker:
      cacheFrom:
      - us-docker.pkg.dev/my-project-id/repo-name/market-data-transcoder
  - image: us-docker.pkg.dev/my-project-id/repo-name/wget-init
    context: wget-init
    docker:
      cacheFrom:
      - us-docker.pkg.dev/my-project-id/repo-name/wget-init
  tagPolicy:
    sha256: {}
  local: {}
# defines where to find the code at build time and where to push the resulting image    
manifests:
   kpt:
      - kubernetes-manifests
deploy:
  kpt:
    applyFlags:
      - "--inventory-policy=adopt"
      - "--force-conflicts"
#use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: my-project-id
    tagPolicy:
      customTemplate:
        template: '{{.DATE}}_{{.COMMIT}}'
        components:
        - name: DATE
          dateTime:
            format: "2006-01-02"
            timezone: UTC
        - name: COMMIT
          gitCommit:
            variant: AbbrevCommitSha